# 1D Array with Numpy

In [1]:
import numpy as np
import torch

t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print(f"Rank of t: {t.ndim}")
print(f"Shape of t: {t.shape}")

Rank of t: 1
Shape of t: (7,)


# 2D Array with Numpy

In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
print(t)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [7]:
print(f"Rank of t: {t.ndim}")
print(f"Shape of t: {t.shape}")

Rank of t: 2
Shape of t: (3, 3)


# PyTorch에서 Tensor는?
## 1D Array

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5.])
print(t)

tensor([0., 1., 2., 3., 4., 5.])


In [11]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape

1
torch.Size([6])
torch.Size([6])


# 2D Array

In [12]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                    ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape

2
torch.Size([4, 3])
torch.Size([4, 3])


**아래 코드를 주목하자.**

In [18]:
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

In [19]:
# same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[3, 2]])
print(m1 + m2)

tensor([[6., 5.]])


In [20]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 3]])
m2 = torch.FloatTensor([3]) # 브로드캐스팅으로 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 6.]])


In [27]:
# 2 x 1 Vec + 1 x 2 Vec
m1 = torch.FloatTensor([[3, 3]]) # (1,2) => (2,2)
m2 = torch.FloatTensor([[3], [4]]) # (2,1) => (2,2)
print(m1 + m2)

tensor([[6., 6.],
        [7., 7.]])


In [28]:
print(m1 * m2)
print(m1.T * m2)

tensor([[ 9.,  9.],
        [12., 12.]])
tensor([[ 9.],
        [12.]])


## Mul vs. Matmul
mul(): Multiplies each element of the input `input` with the scalar `other` and returns a new resulting tensor.

matmul(): Matrix product of two tensors.

In [29]:
print()
print('-------------')
print('Mul vs Matmul')
print('MatMul: 행렬곱 \nMul: 원소별 곱')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
MatMul: 행렬곱 
Mul: 원소별 곱
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [30]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [31]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [33]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
print(t.mean()) # 전체 평균
print(t.mean(dim=0)) # 첫번째 차원에서 계산해... 1+3/2와 2+4/2
print(t.mean(dim=1)) # 두번째 차원에서 계산해... 1+2/2와 3+4/2
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# Sum

In [35]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [37]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# Max와 Argmax

In [38]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [39]:
# The max operator returns one value if it is called without an argument.
print(t.max()) # Returns one value: max

tensor(4.)


The max operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [40]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


여기서 t.max(dim=0)[0]의 결과값이 [3., 4.]가 나오는지 알아야 한다.

In [41]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View(Reshape)

In [2]:
t = np.array([[[0, 1, 2],
              [3,4,5]],
             [[6,7,8],
             [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [4]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape) # (2,2,3)-> (4,3)로 reshpae됨.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [6]:
print(ft.view([-1, 1, 3])) #-1은 변동이 일어나기 쉬운 dimension에 사용!
print(ft.view([-1, 1, 3]).shape) # (2,2,3) -> (2x2, 1, 3)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

In [7]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [8]:
print(ft.squeeze())
print(ft.squeeze().shape) # (3,1) => (3,)

tensor([0., 1., 2.])
torch.Size([3])
